Add "r: devel" to .travis.yml
Hope that this fixes the following error in travis:
Error: package ‘devtools’ was installed by an R version with different internals; 
it needs to be reinstalled for use with this R version